services:
  backend1:
    build:
      context: ./backend # path to backend Dockerfile
    ports: 
     - "8080:8080"

  backend2:
    build:
      context: ./backend
    ports:
      - "8081:8080"

  auth-backend:
    build:
      context: ./auth-backend
    ports:
      - "4000:4000"

  client1:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend1

  client2:
    build:
      context: ./client_2
    ports: 
      - "3001:3000"
    depends_on:
      - backend2
